# Jekyll's site settings
# https://jekyllrb.com/docs/configuration/

# Plugins
plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Location
source: src/
destination: public_html/
